- name: Configure EC2 instance
  hosts: app_server
  become: true
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: 'yes'  

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker is started and enabled at boot
      service:
        name: docker
        state: started
        enabled: 'yes'  
